#Playbook with secrets refered from a file
#Created by: Aswin KS
---
- name: Example Playbook with Vault secret refered from a file
  hosts: localhost
  connection: local  # To run directly on local host
  gather_facts: false

  vars_files:
      - my-secret-pass.yml
  tasks:
   
    - name: Display the password 
      debug:
        var: password


  #Command to run this playbook: ansible-playbook playbook_with_secret1.yml --ask-vault-pass
  #Provide the vault password
