#Created by Aswin KS
#install application based on OS distribution
---
- hosts: all
  become: true
  tasks:

   - name: installing software for Cent OS
     yum: 
      name:
       - vim
       - wget
      state: present
     when: ansible_distribution == "CentOS"


   - name: installing software  for ubuntu systems
     apt: 
      name:
       - vim
       - wget
      state: present
     when: ansible_distribution == "Ubuntu"