#Generate a CSV file that container details of server
#Created by Aswin KS
---
- name: Gather Server Facts and Save as CSV
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Gather Server Facts
      setup:
        filter: "ansible_facts"

    - name: Create CSV File
      template:
        src: facts_template.j2  #template file is present in the present working directory
        dest: /home/aswin/server_inventory.csv
