#Created by Aswin KS
#Copy a file from ansible host to all other nodes

---
- hosts: all
  become: true
  tasks:
   - name: Copy a file to remote server
     copy:
      src: /tmp/sourcefile   
      dest: /tmp/
      backup: yes     // to take a backup of original the file if it already present in destination