//  Changing password expiry date in linux

---
- hosts: all
  become: yes
  vars:
    users:
     - username: "a"
     - username: "b"
     - username: "c"
  tasks:
    - name : Changing user password expiry  date
      shell:
        chage -M 30 "{{ item.username }}"
      with_items: "{{users}}"

