---
- hosts: all
  become: yes
  vars:
    users:
     - username: "a"
     - username: "b"
     - username: "c"
  tasks:
    - name : Creating users and assigning a password
      user:
        name: "{{item.username }}"
        create_home: yes
        state: present
        password: $6$CrjQS3jVDGphfLMC$Vrcfrnxrw.SIM95e7kmKvxjannNYCrpPEME4d1ua4cmHqRICXFTo0Wvbp/NBncetdNMDCaDfBGiSsq5gj9ZFt0
        update_password: on_create
      with_items: "{{users}}"



      //To create a hash password :


      openssl passwd -6 -stdin



      //

      update_password   :  always will update passwords if they differ. on_create will only set the password for newly created users.